version: '3.8'

services:
  zara-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3060:3060"
    environment:
      - NODE_ENV=production
      - PORT=3060
    restart: unless-stopped
